// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlC1VD4NQToGW9_yKrP8iZP_bj0NmcR2g',
    appId: '1:502258866519:web:210adfa4809d8d25e3c612',
    messagingSenderId: '502258866519',
    projectId: 'thirdrail-1e56e',
    authDomain: 'thirdrail-1e56e.firebaseapp.com',
    storageBucket: 'thirdrail-1e56e.firebasestorage.app',
    measurementId: 'G-53ZJJY02X7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3w3ELPnR-7Ybfrxe5qD8MbQ361413b1Q',
    appId: '1:502258866519:android:a18c01611fd6b687e3c612',
    messagingSenderId: '502258866519',
    projectId: 'thirdrail-1e56e',
    storageBucket: 'thirdrail-1e56e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-N09BqDjcPa_2jEJGhBaDtYh8AUqPeRQ',
    appId: '1:502258866519:ios:999df50ba02ac33ae3c612',
    messagingSenderId: '502258866519',
    projectId: 'thirdrail-1e56e',
    storageBucket: 'thirdrail-1e56e.firebasestorage.app',
    iosBundleId: 'com.example.thirdrail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-N09BqDjcPa_2jEJGhBaDtYh8AUqPeRQ',
    appId: '1:502258866519:ios:999df50ba02ac33ae3c612',
    messagingSenderId: '502258866519',
    projectId: 'thirdrail-1e56e',
    storageBucket: 'thirdrail-1e56e.firebasestorage.app',
    iosBundleId: 'com.example.thirdrail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlC1VD4NQToGW9_yKrP8iZP_bj0NmcR2g',
    appId: '1:502258866519:web:011248952b4f7fd4e3c612',
    messagingSenderId: '502258866519',
    projectId: 'thirdrail-1e56e',
    authDomain: 'thirdrail-1e56e.firebaseapp.com',
    storageBucket: 'thirdrail-1e56e.firebasestorage.app',
    measurementId: 'G-WE144J1XXL',
  );
}
